config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/search' => 'search#search'
  # お問い合わせフォーム
  get  '/contact/index' =>'messages#index'
  post '/contact/confirm' => 'messages#confirm'
  post '/contact/done' => 'messages#done'
  # チャットルーム
  resources :rooms, only: [:index, :create, :show]

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, only: [:show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    # get '/follows' => 'relationships#follower', as: 'follows'
    # get '/followers' => 'relationships#followed', as: 'followers'
  end
  get '/users/:id/timeline' => 'users#timeline', as: 'user_timeline'
  get '/user/confirm' => 'users#confirm'
  # 退会用のアクション
  put '/users/:id/hide' => 'users#hide', as: 'user_hide'

  resources :idols, only: [:index, :show, :new, :create, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    delete '/ajax_favorites' => 'favorites#ajax_destroy'
    post '/ajax_favorites' => 'favorites#ajax_create'
  end
  resources :places, only: [:index, :show, :new, :create, :edit, :update] do
    resources :place_photos, only: [:show, :new, :create, :destroy]
    resources :place_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    delete '/ajax_bookmarks' => 'bookmarks#ajax_destroy'
    post '/ajax_bookmarks' => 'bookmarks#ajax_create'
  end
  resources :events do
    resources :event_photos, only: [:show, :new, :create, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
    resources :event_comments, only: [:create, :destroy]
    resource :event_registers, only: [:create, :destroy]
  end

  # letter_opener用のルーティング
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/idol.rb
class Idol < ApplicationRecord
  mount_uploader :image_id, ImagesUploader

  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :user_id, presence: true
  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :about, length: { maximum: 140 }
  validates :official_site, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true
  validates :official_twitter, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true
  validates :official_youtube, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true
end

app/controllers/idols_controller.rb
class IdolsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_calender, only: %i[index new create]
  before_action :set_idol_calender, only: %i[show edit update]

  def index
    @idols = Idol.all
  end

  def show
    @idol = Idol.find(params[:id])
    @event_photos = EventPhoto.includes(:event).where(events: { idol_id: @idol.id })
    @next_events = Event.where(idol_id: params[:id]).where('start_date >= ?', Date.today).order(:start_date)
    @past_events = Event.where(idol_id: params[:id]).where('start_date < ?', Date.today).order(:start_date)
  end

  def new
    @idol = Idol.new
  end

  def create
    @idol = Idol.new(idol_params)
    @idol.user_id = current_user.id
    if @idol.save
      redirect_to idol_path(@idol), notice: 'アイドルの登録が完了しました！'
    else
      render :new
    end
  end

  def edit
    @idol = Idol.find(params[:id])
  end

  def update
    @idol = Idol.find(params[:id])
    @idol.user_id = current_user.id
    if @idol.update(idol_params)
      redirect_to idol_path(@idol), notice: 'アイドルの編集が完了しました！'
    else
      render :edit
    end
  end

  def set_idol_calender
    @events = Event.where(idol_id: params[:id])
    @event_array = []
    @events.each do |event|
      ev = {}
      ev['title'] = event.title
      ev['start'] = event.start_date
      ev['end'] = event.end_date
      ev['url'] = event_url(event, format: :html)
      @event_array << ev
    end
    gon.events = @event_array
  end

  private

  def idol_params
    params.require(:idol).permit(:user_id, :name, :about, :image_id,
                                 :official_site, :official_twitter, :official_youtube)
  end
end

app/helpers/idols_helper.rb
module IdolsHelper
end

app/views/idols/_ajax_index.html.erb
<% idols.each do |idol| %>
  <div class="list-box idol-box">

    <!-- 1.image_id→2.default_image→3.no_imageの順に表示 -->
    <% if idol.image_id? %>
      <%= image_tag idol.image_id.to_s, size: "250x270" %>
    <% elsif idol.default_image? %>
      <%= idol.default_image.html_safe %>
    <% else %>
      <%= image_tag "no_image.jpg", size: "250x270" %>
    <% end %>
    <span class="list-title"><%= link_to idol.name, idol_path(idol) %></span>

    <!-- お気に入りボタン -->
    <% if user_signed_in? %>
      <% if idol.favorited_by?(current_user) %>
        <%= link_to "お気に入り解除", idol_ajax_favorites_path(idol.id), method: :delete, remote: true, class: "glyphicon glyphicon-heart-empty click-btn click-btn-success" %>
      <% else %>
        <%= link_to "お気に入り登録", idol_ajax_favorites_path(idol.id), method: :post, remote: true, class: "glyphicon glyphicon-heart-empty click-btn click-btn-danger" %>
      <% end %>
    <% else %>
      <%= link_to "お気に入り登録", idol_ajax_favorites_path(idol.id), method: :post , class: "glyphicon glyphicon-heart-empty click-btn click-btn-danger" %>
    <% end %>

  </div>
<% end %>

app/views/idols/_index.html.erb
<% idols.each do |idol| %>
  <div class="list-box idol-box">

    <!-- 1.image_id→2.default_image→3.no_imageの順に表示 -->
    <% if idol.image_id? %>
      <%= image_tag idol.image_id.to_s, size: "250x270" %>
    <% elsif idol.default_image? %>
      <%= idol.default_image.html_safe %>
    <% else %>
      <%= image_tag "no_image.jpg", size: "250x270" %>
    <% end %>
    <span class="list-title"><%= link_to idol.name, idol_path(idol) %></span>

    <!-- お気に入りボタン -->
    <%= render 'favorites/favorite', idol: idol %>

  </div>
<% end %>

app/views/idols/edit.html.erb
<% provide(:title, "アイドル編集(#{@idol.name})") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar"%>
  </div>

  <div class="col-xs-8">
    <h2 class="heading"><span>アイドル編集</span>&emsp;<%= @idol.name %></h2>
    <hr>

    <div class="row">
      <%= form_for @idol, url: idol_path, method: :patch do |f| %>

      <%= render 'layouts/errors', obj: @idol %>

        <!-- 画像投稿機能 -->
        <div class="col-md-6 col-xs-12 photo">
          <% if @idol.image_id? %>
            <%= image_tag @idol.image_id.to_s, size: "360x360" %>
          <% elsif @idol.default_image? %>
            <%= @idol.default_image.html_safe %>
          <% else %>
            <%= image_tag "no_image.jpg", size: "360x360" %>
          <% end %>
          <%= f.file_field :image_id %>
          <!-- 吹き出し -->
          <div class="balloon-top">
            <p>現場で撮影した写真を<br>投稿してみましょう！</p>
          </div>
        </div>

        <!-- 情報入力フォーム -->
        <div class="col-md-6 col-xs-12">
          <table>
            <tr>
              <td><%= f.label :アイドル名 %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :About %></td>
              <td><%= f.text_area :about, rows:"5" %></td>
            </tr>
            <tr>
              <td><%= f.label :公式サイト %></td>
              <td><%= f.text_field :official_site %></td>
            </tr>
            <tr>
              <td><%= f.label :Twitter %></td>
              <td><%= f.text_field :official_twitter %></td>
            </tr>
            <tr>
              <td><%= f.label :Youtube %></td>
              <td><%= f.text_field :official_youtube %></td>
            </tr>
          </table>
          <hr>
          <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/idols/index.html.erb
<% provide(:title, "アイドル一覧") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar" %>
  </div>

  <div class="col-xs-8">
    <div class="head">
      <h2 class="index-heading">
        <span>アイドル一覧</span>
      </h2>
      <%= link_to "新規アイドル登録", new_idol_path, class: "click-btn click-btn-add" %>
    </div>
    <hr>

    <div class="idols_index">
      <%= render "ajax_index", idols: @idols %>
    </div>
  </div>

</div>

app/views/idols/new.html.erb
<% provide(:title, "アイドル新規作成") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar"%>
  </div>

  <div class="col-xs-8">
    <h2 class="heading"><span>アイドル新規登録</span></h2>
    <hr>

    <div class="row">
      <%= form_for @idol, url: idols_path do |f| %>

      <%= render 'layouts/errors', obj: @idol %>

        <!-- 画像投稿機能 -->
        <div class="col-md-6 col-xs-12 new-photo">
          <%= f.label :画像 %>
          <%= f.file_field :image_id %>
          <!-- 吹き出し -->
          <div class="balloon-top">
            <p>現場で撮影した写真を<br>投稿してみましょう！</p>
          </div>
        </div>

        <!-- 情報入力フォーム -->
        <div class="col-md-6 col-xs-12">
          <table>
            <tr>
              <td><%= f.label :アイドル名 %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :About %></td>
              <td><%= f.text_area :about, rows:"5" %></td>
            </tr>
            <tr>
              <td><%= f.label :公式サイト %></td>
              <td><%= f.text_field :official_site %></td>
            </tr>
            <tr>
              <td><%= f.label :Twitter %></td>
              <td><%= f.text_field :official_twitter %></td>
            </tr>
            <tr>
              <td><%= f.label :Youtube %></td>
              <td><%= f.text_field :official_youtube %></td>
            </tr>
          </table>
          <%= f.submit "新規登録", class: "btn btn-lg btn-primary" %>
        </div>

      <% end %>
    </div>
  </div>

</div>

app/views/idols/show.html.erb
<% provide(:title, "アイドル詳細(#{@idol.name})") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar"%>
  </div>

  <div class="col-xs-8">
    <h2 class="heading"><span>アイドル詳細</span>&emsp;<%= @idol.name %></h2>
    <hr>

    <div class="row">

      <!-- 画像 -->
      <div class="col-md-7 col-xs-12 photo">
        <% if @idol.image_id? %>
          <%= image_tag @idol.image_id.to_s, size: "360x360" %>
        <% elsif @idol.default_image? %>
          <%= @idol.default_image.html_safe %>
        <% else %>
          <%= image_tag "no_image.jpg", size: "360x360" %>
        <% end %>
      </div>

      <!-- 詳細 -->
      <div class="col-md-5 col-xs-12">
        <h4>About</h4>
        <p><%= @idol.about %></p>
        <% if @idol.official_site? %>
          <%= link_to "公式サイト", @idol.official_site %>
        <% end %>
        <div class="social-icon">
          <% if @idol.official_twitter? %>
            <%= link_to @idol.official_twitter do %>
              <img src="<%= asset_path "twitter.png" %>" alt="Twitter">
            <% end %>
          <% end %>
          <% if @idol.official_youtube? %>
            <%= link_to @idol.official_youtube do %>
              <img src="<%= asset_path "youtube.png" %>" alt="Youtube">
            <% end %>
          <% end %>
          <div class="twitter-share">
          　<a href="//twitter.com/share" class="twitter-share-button" data-text="<%= @idol.name %>|idol places-アイドル現場情報共有サイト-" data-url="<%= request.url %>" data-lang="ja">
           Tweet
           </a>
          </div>
        </div>
      </div>

      <!-- イベント写真 -->
      <% if @event_photos.exists? %>
        <div class="row">
          <div class="col-xs-12">
            <hr>
            <% @event_photos.each do |event_photo| %>
              <%= link_to event_event_photo_path(event_id: event_photo.event.id, id: event_photo.id) do %>
                <%= image_tag event_photo.image_id.to_s, size: "60x40" %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>

    </div>
    <hr>

    <!-- いいね機能 -->
    <div class="row">
      <div class="col-xs-6">
        <%= render 'favorites/favorite', idol: @idol %>
      </div>

      <!-- 編集ボタン -->
      <div class="col-xs-6">
        <%= link_to "編集する", edit_idol_path(@idol.id), class: "click-btn click-btn-warning" %>
      </div>
    </div>
    <hr>

    <div class="row">
      <h3>関連イベント情報</h3>
      <%= render 'events/index', events: @next_events %>
    </div>

    <% if @past_events.exists? %>
      <div class="row">
        <a class="click-btn click-btn-info" data-toggle="collapse" href="#collapse-past-events">
          過去イベント
        </a>
        <div class="collapse" id="collapse-past-events">
          <div class="well">
            <%= render 'events/index', events: @past_events %>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>