config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/search' => 'search#search'
  # お問い合わせフォーム
  get  '/contact/index' =>'messages#index'
  post '/contact/confirm' => 'messages#confirm'
  post '/contact/done' => 'messages#done'
  # チャットルーム
  resources :rooms, only: [:index, :create, :show]

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, only: [:show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    # get '/follows' => 'relationships#follower', as: 'follows'
    # get '/followers' => 'relationships#followed', as: 'followers'
  end
  get '/users/:id/timeline' => 'users#timeline', as: 'user_timeline'
  get '/user/confirm' => 'users#confirm'
  # 退会用のアクション
  put '/users/:id/hide' => 'users#hide', as: 'user_hide'

  resources :idols, only: [:index, :show, :new, :create, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    delete '/ajax_favorites' => 'favorites#ajax_destroy'
    post '/ajax_favorites' => 'favorites#ajax_create'
  end
  resources :places, only: [:index, :show, :new, :create, :edit, :update] do
    resources :place_photos, only: [:show, :new, :create, :destroy]
    resources :place_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    delete '/ajax_bookmarks' => 'bookmarks#ajax_destroy'
    post '/ajax_bookmarks' => 'bookmarks#ajax_create'
  end
  resources :events do
    resources :event_photos, only: [:show, :new, :create, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
    resources :event_comments, only: [:create, :destroy]
    resource :event_registers, only: [:create, :destroy]
  end

  # letter_opener用のルーティング
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :idol
  belongs_to :place
  has_many :event_photos, dependent: :destroy
  has_many :event_comments, dependent: :destroy
  has_many :event_registers, dependent: :destroy

  enum genre: { リリースイベント: 0, 単独ライブ: 1, 対バン: 2, 特典会: 3, 生誕祭: 4, 公開収録: 5, 舞台: 6, 配信: 7, その他: 8 }

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true
  validates :open_date, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  # default_scope -> { order(start_date: :desc) }

  def event_registered_by?(user)
    event_registers.where(user_id: user.id).exists?
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_event, only: %i[show edit update destroy]
  before_action :set_calender, only: %i[new create]
  before_action :set_event_calender, only: %i[show edit update]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order(:start_date)
    @event_array = []
    @events.each do |event|
      ev = {}
      ev['title'] = event.title
      ev['start'] = event.start_date
      ev['end'] = event.end_date
      ev['url'] = event_url(event, format: :html)
      @event_array << ev
    end
    gon.events = @event_array
    # 今月のイベントの情報取得
    this_month = Date.today.all_month
    @this_month_events = @events.where(start_date: this_month).where('start_date >= ?', Date.today).order(:start_date)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @idol = Idol.find(@event.idol_id)
    @place = Place.find(@event.place_id)
    @event_photos = EventPhoto.where(event_id: @event.id)
    @event_comment = EventComment.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'イベントの登録が完了しました！' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'イベントの編集が完了しました！' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'イベントの削除が完了しました！' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_event_calender
    @event_array = []
    ev = {}
    ev['title'] = @event.title
    ev['start'] = @event.start_date
    ev['end'] = @event.end_date
    ev['url'] = event_url(@event, format: :html)
    @event_array << ev
    gon.events = @event_array
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:user_id, :idol_id, :place_id, :title, :genre, :body, :open_date, :start_date, :end_date)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="col-xs-12">
  <%= form_with(model: event, local: true) do |form| %>

    <%= render 'layouts/errors', obj: event %>

    <table>
      <tr>
        <td><%= form.label :イベント名 %></td>
        <td><%= form.text_field :title %></td>
      </tr>
      <tr>
        <td><%= form.label :イベントジャンル %></td>
        <td><%= form.select :genre, Event.genres.keys.map {|k| [k, k]}, {include_blank: '---'} %></td>
      </tr>
      <tr>
        <td><%= form.label :"イベント内容(リンク)" %></td>
        <td><%= form.text_field :body %></td>
      </tr>
      <tr>
        <td><%= form.label :アイドル名 %></td>
        <td><%= form.collection_select :idol_id, Idol.all.order(:name), :id, :name, {include_blank: '---'} %></td>
      </tr>
      <tr>
        <td><%= form.label :場所名 %></td>
        <td><%= form.collection_select :place_id, Place.all.order(:name), :id, :name, {include_blank: '---'} %></td>
      </tr>
      <tr>
        <td><%= form.label :開場時間 %></td>
        <td><%= form.text_field :open_date, data: { :date_format => 'YYYY/MM/DD HH:mm' }, :class => 'form-control datetimepicker', placeholder: 'YYYY/MM/DD hh:mm' %></td>
      </tr>
      <tr>
        <td><%= form.label :開始予定時間 %></td>
        <td><%= form.text_field :start_date, data: { :date_format => 'YYYY/MM/DD HH:mm' }, :class => 'form-control datetimepicker', placeholder: 'YYYY/MM/DD hh:mm' %></td>
      </tr>
      <tr>
        <td><%= form.label :終了予定時間 %></td>
        <td><%= form.text_field :end_date, data: { :date_format => 'YYYY/MM/DD HH:mm' }, :class => 'form-control datetimepicker', placeholder: 'YYYY/MM/DD hh:mm' %></td>
      </tr>
    </table>

    <div class="actions">
      <% if params[:controller] == 'events' && %w(new create).include?(params[:action]) %>
        <%= form.submit "新規登録" %>
      <% else %>
        <%= form.submit "編集" %>
      <% end %>
    </div>
  <% end %>

  <hr>
  <div>
    <%= link_to "新規アイドル登録", new_idol_path, class: "click-btn click-btn-add" %>
    <%= link_to "新規場所登録", new_place_path, class: "click-btn click-btn-add" %>
  </div>
  <br>
  <br>
  <div class="balloon-top">
    <p>アイドルと場所が見つからない場合は<br>こちらから登録してください。</p>
  </div>

</div>

app/views/events/_index.html.erb
<table class="table table-hover">

  <thead>
    <tr>
      <th>イベント名</th>
      <th>アイドル名</th>
      <th>場所名</th>
      <th>開始予定時間</th>
      <th>終了予定時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= link_to event.title, event_path(event) %></td>
        <td><%= link_to event.idol.name, idol_path(event.idol.id) %></td>
        <td><%= link_to event.place.name, place_path(event.place.id) %></td>
        <td><%= l event.start_date %></td>
        <td><%= l event.end_date %></td>

        <% if user_signed_in? %>
          <td>
            <% if event.event_registered_by?(current_user) %>
            <%= link_to "解除", event_event_registers_path(event.id), method: :delete , class: "click-btn click-btn-success" %>
            <% else %>
            <%= link_to "登録", event_event_registers_path(event.id), method: :post , class: "click-btn click-btn-danger" %>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to "登録", event_event_registers_path(event.id), method: :post , class: "click-btn click-btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/events/edit.html.erb
<% provide(:title, "イベント編集(#{@event.title})") %>

<div class="col-xs-4">
  <%= render "layouts/sidebar"%>
</div>

<div class="col-xs-8">
  <h2 class="heading"><span>イベント編集</span></h2>
  <hr>
  <%= render 'form', event: @event %>
  <br>
</div>

app/views/events/index.html.erb
<% provide(:title, "イベント一覧") %>

<h2 class="heading"><span>イベントカレンダー</span></h2>
<hr>

<div id="calendar"></div>
<hr>

<h3>今月のイベント</h3>
<%= render "index", events: @this_month_events %>
<br>
<%= link_to 'イベント新規作成', new_event_path, class: "click-btn click-btn-add" %>

app/views/events/new.html.erb
<% provide(:title, "イベント新規作成") %>

<div class="col-xs-4">
  <%= render "layouts/sidebar"%>
</div>

<div class="col-xs-8">
  <h2 class="heading"><span>イベント新規登録</span></h2>
  <hr>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<% provide(:title, "イベント詳細(#{@event.title})") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar"%>
  </div>

  <div class="col-xs-8">
    <h2 class="heading"><span>イベント詳細</span></h2>
    <hr>

    <div class="row">

      <!-- 画像 -->
      <div class="col-md-6 col-xs-12">
        <% if @event_photos.exists? %>
          <ul class="bxslider">
            <% @event_photos.each do |event_photo| %>
              <li>
                <%= link_to event_event_photo_path(event_id: @event.id, id: event_photo.id) do %>
                  <%= image_tag event_photo.image_id.to_s, title: "Photo by #{link_to event_photo.user.name, user_path(event_photo.user)}" %>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% elsif @idol.image_id? %>
          <%= image_tag @idol.image_id.to_s, size: "300x300" %>
        <% elsif @idol.default_image? %>
          <%= @idol.default_image.html_safe %>
        <% else %>
          <%= image_tag "no_image.jpg", size: "300x300" %>
        <% end %>
      </div>
      <!-- 詳細 -->
      <div class="col-md-6 col-xs-12">
        <p>
          <strong>イベント名:</strong>
          <%= @event.title %>
        </p>

        <p>
          <strong>イベントジャンル:</strong>
          <%= @event.genre %>
        </p>

        <p>
          <strong>イベント内容(リンク):</strong>
          <%= link_to @event.body, @event.body %>
        </p>

        <p>
          <strong>アイドル名:</strong>
          <%= link_to @idol.name, idol_path(@idol) %>
        </p>

        <p>
          <strong>場所名:</strong>
          <%= link_to @place.name, place_path(@place) %>
        </p>

        <p>
          <strong>開場時間:</strong>
          <%= l @event.open_date %>
        </p>

        <p>
          <strong>開始予定時間:</strong>
          <%= l @event.start_date %>
        </p>

        <p>
          <strong>終了予定時間:</strong>
          <%= l @event.end_date %>
        </p>
      </div>
      <div class="twitter-share">
      　<a href="//twitter.com/share" class="twitter-share-button" data-text="<%= @event.title %>|idol places-アイドル現場情報共有サイト-" data-url="<%= request.url %>" data-lang="ja">
       Tweet
       </a>
      </div>
    </div>

    <!-- イベント写真 -->
    <% if @event_photos.exists? %>
    <hr>
      <div class="row">
        <div class="col-xs-12">
          <% @event_photos.each do |event_photo| %>
            <%= link_to event_event_photo_path(event_id: @event.id, id: event_photo.id) do %>
              <%= image_tag event_photo.image_id.to_s, size: "60x40" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <hr>

    <!-- 登録(解除)ボタン -->
    <div class="row">
      <div class="col-xs-6">
        <% if user_signed_in? %>
          <% if @event.event_registered_by?(current_user) %>
            <%= link_to "解除", event_event_registers_path(@event.id), method: :delete , class: "click-btn click-btn-success" %>
          <% else %>
            <%= link_to "イベント登録", event_event_registers_path(@event.id), method: :post , class: "click-btn click-btn-danger" %>
          <% end %>
        <% else %>
          <%= link_to "イベント登録", event_event_registers_path(@event.id), method: :post , class: "click-btn click-btn-danger" %>
        <% end %>
        <%= link_to "写真追加", new_event_event_photo_path(@event.id), class: "click-btn click-btn-info" %>
      </div>
      <!-- 編集ボタン -->
      <div class="col-xs-6">
        <%= link_to "編集する", edit_event_path(@event.id), class: "click-btn click-btn-warning" %>
      </div>
    </div>
    <hr>

    <!-- イベントコメントフォーム/一覧 -->
    <div class="row">
      <div id ="event_comments_<%= @event.id %>">
        <%= render "event_comments/comment", event: @event, event_comment: @event_comment %>
      </div>
    </div>

  </div>
</div>