config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/search' => 'search#search'
  # お問い合わせフォーム
  get  '/contact/index' =>'messages#index'
  post '/contact/confirm' => 'messages#confirm'
  post '/contact/done' => 'messages#done'
  # チャットルーム
  resources :rooms, only: [:index, :create, :show]

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, only: [:show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    # get '/follows' => 'relationships#follower', as: 'follows'
    # get '/followers' => 'relationships#followed', as: 'followers'
  end
  get '/users/:id/timeline' => 'users#timeline', as: 'user_timeline'
  get '/user/confirm' => 'users#confirm'
  # 退会用のアクション
  put '/users/:id/hide' => 'users#hide', as: 'user_hide'

  resources :idols, only: [:index, :show, :new, :create, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    delete '/ajax_favorites' => 'favorites#ajax_destroy'
    post '/ajax_favorites' => 'favorites#ajax_create'
  end
  resources :places, only: [:index, :show, :new, :create, :edit, :update] do
    resources :place_photos, only: [:show, :new, :create, :destroy]
    resources :place_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    delete '/ajax_bookmarks' => 'bookmarks#ajax_destroy'
    post '/ajax_bookmarks' => 'bookmarks#ajax_create'
  end
  resources :events do
    resources :event_photos, only: [:show, :new, :create, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
    resources :event_comments, only: [:create, :destroy]
    resource :event_registers, only: [:create, :destroy]
  end

  # letter_opener用のルーティング
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/place_comment.rb
class PlaceComment < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :user_id, presence: true
  validates :place_id, presence: true
  validates :body, presence: true, length: { maximum: 140 }
  validates :rate, presence: true

  default_scope -> { order(created_at: :desc) }
end

app/controllers/place_comments_controller.rb
class PlaceCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place_comment = PlaceComment.new(place_comment_params)
    @place_comment.user_id = current_user.id
    @place_comment.place_id = @place.id
    # NaturalLanguage(感情分析)でコメントをスコア化(2.5未満は2.5へ)
    @place_comment_score = Language.get_data(place_comment_params[:body]).round(1)
    @place_comment.rate = if @place_comment_score < 0
                            2.5
                          elsif @place_comment_score.between?(0.1, 0.2)
                            3.0
                          elsif @place_comment_score.between?(0.3, 0.4)
                            3.5
                          elsif @place_comment_score.between?(0.5, 0.6)
                            4.0
                          elsif @place_comment_score.between?(0.7, 0.8)
                            4.5
                          else
                            5.0
                          end
    @place_comment.save
    flash.now[:notice] = 'コメントの作成が完了しました！'
    # ajaxのrender用
    @event = Event.where(place_id: params[:id])
  end

  def destroy
    @place_comment = PlaceComment.find(params[:id])
    @place = Place.find(params[:place_id])
    @place_comment.destroy
    flash.now[:notice] = 'コメントの削除が完了しました！'
    # ajaxのrender用
    @place_photos = PlacePhoto.where(place_id: @place.id)
    @new_place_comment = PlaceComment.new
    @event = Event.where(place_id: params[:place_id])
  end

  private

  def place_comment_params
    params.require(:place_comment).permit(:body, :rate)
  end
end

app/helpers/place_comments_helper.rb
module PlaceCommentsHelper
end

app/views/place_comments/_comment_form.html.erb
<% if user_signed_in? %>
  <h3>コメント</h3>
  <%= form_with model: [place, place_comment], url: place_place_comments_path(place.id), method: :post, data: {remote: true} do |f| %>

  <!-- エラーメッセージ -->
  <%= render 'layouts/errors', obj: place_comment %>

    <div class="field">
      <%= f.text_area :body, rows:'2', class:"form-control", placeholder:"コメントをここに" %>
    </div>

    <%= f.submit "送信する", class:"btn btn-lg pull-right" %>
  <% end %>
<% end %>

app/views/place_comments/_comments.html.erb
<!-- コメント一覧 -->
<div class="row">
  <h4 class="comment-count">
    <%= place.place_comments.count %>件のコメント
  </h4>
  <div class="comment-list" id="comments">
    <div class="float-wrapper">

      <ol>
        <% place.place_comments.each do |place_comment| %>
          <li class="comment">
            <div class="comment-body bb">
              <div class="comment-avatar">
                <div class="avatar">

                  <!-- 退会済みユーザーは"no_image"を表示 -->
                  <% if place_comment.user.image_id? && place_comment.user.is_deleted == false %>
                    <%= image_tag place_comment.user.image_id.to_s, size: "60x60" %>
                  <% elsif place_comment.user.provider_image_id? && place_comment.user.is_deleted == false %>
                    <%= image_tag place_comment.user.provider_image_id, size: "60x60" %>
                  <% else %>
                    <%= image_tag "no_image.jpg", size: "60x60" %>
                  <% end %>

                </div>
              </div>
              <div class="comment-text">
                <div class="comment-author clearfix">

                  <!-- 退会済みユーザーは"退会済みユーザー"と表示 -->
                  <% if place_comment.user.is_deleted == true %>
                    <p>退会済みユーザー</p>
                  <% else %>
                    <%= place_comment.user.name %>
                  <% end %>

                  <span class="comment-meta">
                    <span class="comment-date"><%= l place_comment.created_at %></span>
                  </span>
                </div>
                <div class="comment-entry"><%= place_comment.body %></div>
                <div id="reviewed_star_<%= place_comment.id %>">
                </div>
              </div>
              <!-- コメント投稿者のみ削除リンク -->
              <% if user_signed_in? && place_comment.user.id == current_user.id %>
                <%= link_to "削除",place_place_comment_path(place_id: place.id, id: place_comment.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "click-btn click-btn-danger pull-right", remote: true %>
              <% end %>
            </div>

            <script>
              $("#reviewed_star_<%= place_comment.id %>").raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              readOnly: true,
              half: true,
              score: '<%= place_comment.rate %>'
              });
            </script>
          </li>
        <% end %>
      </ol>

    </div>
  </div>
</div>

app/views/place_comments/create.js.erb
<% if @place_comment.save %>
  toastr.success("コメントを作成しました！")
<% end %>

$("#place_comment_form_<%= @place.id %>").html("<%= j(render 'place_comments/comment_form', place: @place, place_comment: @place_comment ) %>");
$("textarea").val("");
$("#place_comments_<%= @place.id %>").html("<%= j(render 'place_comments/comments', place: @place ) %>");

app/views/place_comments/destroy.js.erb
toastr.success("コメントを削除しました！")
$("#place_comment_form_<%= @place.id %>").html("<%= j(render 'place_comments/comment_form', place: @place, place_comment: @new_place_comment ) %>");
$("textarea").val("");
$("#place_comments_<%= @place.id %>").html("<%= j(render 'place_comments/comments', place: @place ) %>");