config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/search' => 'search#search'
  # お問い合わせフォーム
  get  '/contact/index' =>'messages#index'
  post '/contact/confirm' => 'messages#confirm'
  post '/contact/done' => 'messages#done'
  # チャットルーム
  resources :rooms, only: [:index, :create, :show]

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, only: [:show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    # get '/follows' => 'relationships#follower', as: 'follows'
    # get '/followers' => 'relationships#followed', as: 'followers'
  end
  get '/users/:id/timeline' => 'users#timeline', as: 'user_timeline'
  get '/user/confirm' => 'users#confirm'
  # 退会用のアクション
  put '/users/:id/hide' => 'users#hide', as: 'user_hide'

  resources :idols, only: [:index, :show, :new, :create, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    delete '/ajax_favorites' => 'favorites#ajax_destroy'
    post '/ajax_favorites' => 'favorites#ajax_create'
  end
  resources :places, only: [:index, :show, :new, :create, :edit, :update] do
    resources :place_photos, only: [:show, :new, :create, :destroy]
    resources :place_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    delete '/ajax_bookmarks' => 'bookmarks#ajax_destroy'
    post '/ajax_bookmarks' => 'bookmarks#ajax_create'
  end
  resources :events do
    resources :event_photos, only: [:show, :new, :create, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
    resources :event_comments, only: [:create, :destroy]
    resource :event_registers, only: [:create, :destroy]
  end

  # letter_opener用のルーティング
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :image_id, ImagesUploader

  belongs_to :user
  has_many :place_photos, dependent: :destroy
  has_many :place_comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :user_id, presence: true
  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :about, length: { maximum: 140 }
  validates :official_site, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_calender, only: %i[index new create]
  before_action :set_place_calender, only: %i[show edit update]

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @place_photos = PlacePhoto.where(place_id: @place.id)
    @next_events = Event.where(place_id: params[:id]).where('start_date >= ?', Date.today).order(:start_date)
    @place_comment = PlaceComment.new
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.save
      redirect_to place_path(@place), notice: '場所の登録が完了しました！'
    else
      render :new
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    @place.user_id = current_user.id
    if @place.update(place_params)
      redirect_to place_path(@place), notice: '場所の編集が完了しました！'
    else
      render :edit
    end
  end

  def set_place_calender
    @events = Event.where(place_id: params[:id])
    @event_array = []
    @events.each do |event|
      ev = {}
      ev['title'] = event.title
      ev['start'] = event.start_date
      ev['end'] = event.end_date
      ev['url'] = event_url(event, format: :html)
      @event_array << ev
    end
    gon.events = @event_array
  end

  private

  def place_params
    params.require(:place).permit(:user_id, :name, :address, :about, :official_site, :image_id)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_ajax_index.html.erb
<% places.each do |place| %>
  <div class="list-box place-box">
    <% if place.image_id? %>
      <%= image_tag place.image_id.to_s, size: "240x180" %>
    <% else %>
      <%= image_tag "no_image.jpg", size: "240x180" %>
    <% end %>
    <span class="list-title"><%= link_to place.name, place_path(place) %></span>

      <!-- お気に入りボタン -->
      <% if user_signed_in? %>

        <% if place.bookmarked_by?(current_user) %>
          <%= link_to "お気に入り解除", place_ajax_bookmarks_path(place.id), method: :delete, remote: true, class: "glyphicon glyphicon-heart-empty click-btn click-btn-success" %>
        <% else %>
          <%= link_to "お気に入り登録", place_ajax_bookmarks_path(place.id), method: :post, remote: true, class: "glyphicon glyphicon-heart-empty click-btn click-btn-danger" %>
        <% end %>

      <% else %>
        <%= link_to "お気に入り登録", place_ajax_bookmarks_path(place.id), method: :post, class: "glyphicon glyphicon-heart-empty click-btn click-btn-danger" %>
    <% end %>
  </div>
<% end %>

app/views/places/_google_map.html.erb
<h2>Google MAP</h2>
<div id='map' class="<%= place.name %>"></div>
<style>
  #map{
    height: 250px;
  }
</style>

<script src="//maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>

<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/

let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()
  geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
    if (status == 'OK') {
      // map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
          });
      } else {
          alert('Geocode was not successful for the following reason: ' + status);
          }
      });

      map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -34.397, lng: 150.644},
      zoom: 14
      });
    }

    function codeAddress(){
    // 入力を取得
    let inputAddress = document.getElementById('address').value;

    // geocodingしたあとmapを移動
    }
  </script>

app/views/places/_index.html.erb
<% places.each do |place| %>
  <div class="list-box place-box">
    <% if place.image_id? %>
      <%= image_tag place.image_id.to_s, size: "240x180" %>
    <% else %>
      <%= image_tag "no_image.jpg", size: "240x180" %>
    <% end %>
    <span class="list-title"><%= link_to place.name, place_path(place) %></span>

    <!-- お気に入りボタン -->
    <%= render 'bookmarks/bookmark', place: place %>
  </div>
<% end %>

app/views/places/edit.html.erb
<% provide(:title, "場所編集(#{@place.name})") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar"%>
  </div>

  <div class="col-xs-8">
    <h2 class="heading"><span>場所編集</span></h2>
    <hr>

    <div class="row">
      <%= form_for @place, url: place_path, method: :patch do |f| %>

      <%= render 'layouts/errors', obj: @place %>

        <!-- 画像投稿機能 -->
        <div class="col-md-6 col-xs-12 photo">
          <% if @place.image_id? %>
            <%= image_tag @place.image_id.to_s, size: "360x240" %>
            <%= f.file_field :image_id %>
          <% else %>
            <%= image_tag "no_image.jpg", size: "360x240" %>
            <%= f.file_field :image_id %>
          <% end %>
          <!-- 吹き出し -->
          <div class="balloon-top">
            <p>現場で撮影した写真を<br>投稿してみましょう！</p>
          </div>
        </div>

        <!-- 情報入力フォーム -->
        <div class="col-md-6 col-xs-12">
          <table>
            <tr>
              <td><%= f.label :場所名 %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :住所 %></td>
              <td><%= f.text_field :address %></td>
            </tr>
            <tr>
              <td><%= f.label :公式サイト %></td>
              <td><%= f.text_field :official_site %></td>
            </tr>
            <tr>
              <td><%= f.label :About %></td>
              <td><%= f.text_area :about, rows:"5" %></td>
            </tr>
          </table>
          <hr>
          <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/places/index.html.erb
<% provide(:title, "場所一覧") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar"%>
  </div>

  <div class="col-xs-8">
    <div class="head">
      <h2 class="index-heading">
        <span>場所一覧</span>
      </h2>
      <%= link_to "新規場所登録", new_place_path, class: "click-btn click-btn-add" %>
    </div>
    <hr>

    <div class="places_index">
      <%= render "ajax_index", places: @places %>
    </div>
  </div>

</div>

app/views/places/new.html.erb
<% provide(:title, "場所新規作成") %>

<div class="row">

  <div class="col-xs-4">
    <%= render "layouts/sidebar"%>
  </div>

  <div class="col-xs-8">
    <h2 class="heading"><span>場所新規登録</span></h2>
    <hr>

    <div class="row">
      <%= form_for @place, url: places_path do |f| %>

      <%= render 'layouts/errors', obj: @place %>

        <!-- 画像投稿機能 -->
        <div class="col-md-6 col-xs-12 new-photo">
          <%= f.label :画像 %>
          <%= f.file_field :image_id %>
          <!-- 吹き出し -->
          <div class="balloon-top">
            <p>現場で撮影した写真を<br>投稿してみましょう！</p>
          </div>
        </div>

        <!-- 情報入力フォーム -->
        <div class="col-md-6 col-xs-12">
          <table>
            <tr>
              <td><%= f.label :場所名 %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :住所 %></td>
              <td><%= f.text_field :address %></td>
            </tr>
            <tr>
              <td><%= f.label :公式サイト %></td>
              <td><%= f.text_field :official_site %></td>
            </tr>
            <tr>
              <td><%= f.label :About %></td>
              <td><%= f.text_area :about, rows:"5" %></td>
            </tr>
          </table>
          <%= f.submit "新規登録", class: "btn btn-lg btn-primary" %>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/places/show.html.erb
<% provide(:title, "場所詳細(#{@place.name})") %>

<div class="row">

  <!-- 地図を表示させる関係でサイドバーのテンプレートを使用しない -->
  <!-- サイドバー -->
  <div class="col-xs-4">
    <!-- カレンダー -->
    <div id="calendar"></div>
    <hr>

    <!-- 検索フォーム -->
    <div class="search-form">
      <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag 'search[content]', '', placeholder: "&#xf002;".html_safe %>
        <%= select_tag 'search[model]', options_for_select({"場所" => "place", "アイドル" => "idol", "イベント" => "event"}) %>
        <% select_tag 'search[method]', options_for_select({"部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect"}) %>
        <%= submit_tag '検索' %>
      <% end %>
    </div>
    <hr>

    <!-- GoogleMap表示 -->
    <!-- 「配信」＝場所がない場合は地図を表示しない -->
    <% if @place.name != "配信" %>
      <div class="row">
        <%= render "places/google_map", place: @place %>
      </div>
    <% end %>
    <!-- GitHub草 -->
    <div class="github center">
      <h3>GitHub Activities</h3>
      <h4><i class="fab fa-github"></i> <%= link_to "skiym-aaa", "https://github.com/skiym-aaa/portfolio" %></h4>
      <img src="https://grass-graph.moshimo.works/images/skiym-aaa.png?rotate=270">
    </div>
  </div>

  <div class="col-xs-8">
    <h2 class="heading"><span>場所詳細</span>&emsp;<%= @place.name %></h2>
    <hr>
    <div class="row">

      <!-- 画像 -->
      <div class="col-md-7 col-xs-12 photo">
        <% if @place_photos.exists? %>
          <ul class="bxslider">
            <% @place_photos.each do |place_photo| %>
              <li>
                <%= link_to place_place_photo_path(place_id: @place.id, id: place_photo.id) do %>
                  <%= image_tag place_photo.image_id.to_s, title: "Photo by #{link_to place_photo.user.name, user_path(place_photo.user)}" %>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% elsif @place.image_id? %>
          <%= link_to @place.image_id.url do %>
            <%= image_tag @place.image_id.to_s, size: "360x240" %>
          <% end %>
        <% else %>
          <img src="<%= asset_path "no_image.jpg" %>" alt="No_Image">
        <% end %>
      </div>

      <!-- 詳細 -->
      <div class="col-md-5 col-xs-12">
        <h4>About</h4>
        <p><%= @place.about %></p>
        <h4>住所</h4>
        <p><%= @place.address %></p>
        <% if @place.official_site? %>
          <%= link_to "公式サイト", @place.official_site %>
        <% end %>
        <div class="twitter-share">
        　<a href="//twitter.com/share" class="twitter-share-button" data-text="<%= @place.name %>|idol places-アイドル現場情報共有サイト-" data-url="<%= request.url %>" data-lang="ja">
         Tweet
         </a>
        </div>
      </div>
    </div>

    <!-- 場所写真 -->
    <% if @place_photos.exists? %>
    <hr>
      <div class="row">
        <div class="col-xs-12">
          <% @place_photos.each do |place_photo| %>
            <%= link_to place_place_photo_path(place_id: @place.id, id: place_photo.id) do %>
              <%= image_tag place_photo.image_id.to_s, size: "60x40" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <hr>

    <!-- お気に入りボタン -->
    <div class="row">
      <div class="col-xs-6">
        <%= render 'bookmarks/bookmark', place: @place %>
        <%= link_to "写真追加", new_place_place_photo_path(@place.id), class: "click-btn click-btn-info" %>
      </div>
      <div class="col-xs-6">
        <%= link_to "編集する", edit_place_path(@place.id), class: "click-btn click-btn-warning" %>
      </div>
    </div>
    <hr>

    <!-- 関連イベント情報 -->
    <div class="row">
      <div class="col-xs-12">
        <h3>関連イベント情報</h3>
        <%= render 'events/index', events: @next_events %>
      </div>
    </div>

    <!-- コメントフォーム -->
    <div class="row">
      <div class="col-xs-12">
        <div id ="place_comment_form_<%=@place.id %>">
          <%= render "place_comments/comment_form", place: @place, place_comment: @place_comment %>
        </div>
      </div>
    </div>
    <hr>

    <!-- コメント一覧 -->
    <div class="row">
      <div class="col-xs-12">
        <div id ="place_comments_<%= @place.id %>">
          <%= render "place_comments/comments", place: @place %>
        </div>
      </div>
    </div>
  </div>
</div>